services:
  - mysql
language: python
sudo: true
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "bash .travis.configure_testdb.sh"
script:
  - "export PYTHONPATH=`pwd` && cd test && echo $PYTHONPATH && pytest"